name: Deploy Infrastructure with Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read   # This is required for checking out the repository

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    env:
      TF_VAR_region: ${{ secrets.TF_VAR_region }}
      TF_VAR_iam_user_name: ${{ secrets.TF_VAR_iam_user_name }}
      TF_VAR_bucket_name: ${{ secrets.TF_VAR_tfstate_bucket_name }}

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{secrets.AWS_ROLE_TO_ASSUME}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false tfplan
